### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [agusrabadan/simple-counter-react#1]
# Revisión - Aprobado :white_check_mark:

## Feedback
- Buen proyecto @agusrabadan 🐱‍💻

## Estilo de código y limpieza
- Bien resuelto

## Mejores prácticas/comentarios
- Muy buen uso del `useState`, de los condicionales y de los comentarios en tu código
- Recuerda que los nombres de los componentes y su archivo .jsx debería ir en mayúsculas  
![Captura de pantalla de 2024-04-22 11-31-08](https://github.com/agusrabadan/traffic-light-react/assets/139759297/e318945e-89e9-416c-8490-790a691ca36c)
- En el componente `Home` has importado un componente `Numbers` que luego no has utilizado 
![Captura de pantalla de 2024-04-22 11-31-51](https://github.com/agusrabadan/traffic-light-react/assets/139759297/e93dd897-4af9-45d0-bec3-c2e4fb627669)

**Comment by agusrabadan** [comment]
Gracias Edo, si, es por que estoy usando el mismo repositorio para varios ejercicios para no tener tantos.
